# Generated by Django 5.0.4 on 2024-04-07 09:41

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Beckend', 'Beckend'), ('Frontend', 'Frontend')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=25, unique=True)),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.coursecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeModel',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False, unique=True)),
                ('theme_name', models.CharField(max_length=25, unique=True)),
                ('theme_body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.coursemodel')),
            ],
        ),
    ]
